### Tested successfully on Ubuntu server 18.04
### Testing on CentOS 7
---
- hosts: localhost
  tasks:
  -  name: resolving time zone issue
     become: yes
     copy:
       src: /usr/share/zoneinfo/US/Pacific
       dest: /etc/localtime
  -  name: Getting epel-release for php72
     become: yes
     yum: pkg=epel-release state=latest
     when: ansible_os_family == "RedHat"
  -  name: RHEL-based will also need yum-utils
     become: yes
     yum: pkg=yum-utils state=latest
     when: ansible_os_family == "RedHat"
  -  name: Getting the remi repo for php7 on RHEL
     become: yes
     shell: yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     when: ansible_os_family == "RedHat"
  -  name: enabling the remi repo for RHEL
     become: yes
     shell: yum-config-manager --enable remi-php72
     when: ansible_os_family == "RedHat"
  -  name: Install all required PHP7 packages on RHEL
     become: yes
     yum: pkg={{ item }} state=latest
     with_items:
     -  httpd
     -  mysql
     -  git
     -  curl
     -  sed
     -  zip
     -  php
     -  php-mysql
     -  php72
     -  php72-php-fpm
     when: ansible_os_family == "RedHat"
  -  name: Install all PHP7 packages on Debian
     become: yes
     apt: pkg={{ item }} state=latest
     with_items:
     -  apache2
     -  mysql-client
     -  git
     -  curl
     -  sed
     -  zip
     -  php
     -  libapache2-mod-php
     -  php-mysql
     -  php7.2-cli
     -  php7.2-curl
     -  php7.2-gd
     -  php7.2-mbstring
     -  php7.2-mysql
     -  php7.2-xml
     when: ansible_os_family == "Debian"
  -  name: Clone affinity
     become: yes
     git: repo=https://github.com/csuntechlab/affinity.git dest=/var/www/html/affinity
  -  name: Give affinity correct permissions
     file:
       path: "/var/www/html/affinity"
       state: directory
       owner: www-data
       group: www-data
       mode: 0755
     become: yes
     when: ansible_os_family == "Debian"
  -  name: Give affinity correct permissions, RHEL version
     file:
       path: "/var/www/html/affinity"
       state: directory
       owner: apache
       group: apache
       mode: 0755
     become: yes
     when: ansible_os_family == "RedHat"
  -  name: download composer
     become: yes
     shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  -  name: install composer
     become: yes
     shell: composer install
     args:
       chdir: /var/www/html/affinity
  -  name: modify mods-enabled
     become: yes
     shell: sed -i "s+DirectoryIndex index.html index.cgi index.pl index.php index.xhtml index.htm+DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm+g" /etc/apache2/mods-enabled/dir.conf
     when: ansible_os_family == "Debian"
  -  name: modify the sites for RHEL
     become: yes
     shell: sed -i "s+DirectoryIndex index.html+DirectoryIndex index.php index.html+g" /etc/httpd/conf/httpd.conf
     when: ansible_os_family == "RedHat"
  -  name: modify sites-available on Debian
     become: yes
     shell: sed -i "s+/var/www/html+/var/www/html/public+g" /etc/apache2/sites-available/000-default.conf
     when: ansible_os_family == "Debian"
  -  name: modify server root in RHEL
     become: yes
     shell: sed -i "s+/var/www/html+/var/www/html/public+g" /etc/httpd/conf/httpd.conf
     when: ansible_os_family == "RedHat"
  -  name: modify apache conf
     become: yes
     shell: sed -i "s+Require all denied+Require all granted+g" /etc/apache2/apache2.conf
     when: ansible_os_family == "Debian"
  -  name: modify the equivalent in RHEL
     become: yes
     shell: sed -i "s+Require all denied+Require all granted+g" /etc/httpd/conf/httpd.conf
     when: ansible_os_family == "RedHat"
  -  name: start Apache on boot on RHEL
     become: yes
     service:
       name: httpd
       state: started
     when: ansible_os_family == "RedHat"
  -  name: start Apache on boot on Debian
     become: yes
     service:
       name: apache2
       state: started
     when: ansible_os_family == "Debian"
